import { defineIngredient } from '../../../schema/defineIngredient'

export default defineIngredient({
  slug: 'crodafos-ces',
  category: 'emulsifier',
  inciName: 'Cetearyl Alcohol (and) Dicetyl Phosphate (and) Ceteth-10 Phosphate',
  nameZh: '鲸蜡硬脂醇（和）磷酸二鲸蜡酯（和）鲸蜡醇聚醚-10磷酸酯',
  tradeNames: [{ name: 'Crodafos CES', supplier: 'Croda' }],
  chemicalClass: {
    zh: '脂肪醇磷酸酯类阴离子/非离子复配乳化蜡体系',
    en: 'Fatty-alcohol phosphate-ester emulsifier blend (anionic/nonionic self-emulsifying wax system)',
  },
  chemicalStructureSummary: {
    zh: '由三部分组成的复配蜡状体系：鲸蜡硬脂醇（C16-18脂肪醇，乳化蜡基质）、磷酸二鲸蜡酯（磷酸与两条C16鲸蜡醇链形成的二酯，保留一个可电离的磷酸基，因而带阴离子性）、以及鲸蜡醇聚醚-10磷酸酯（经10摩尔环氧乙烷乙氧基化的鲸蜡醇再与磷酸成酯，兼具阴离子磷酸头基与非离子PEG链）。三者构成的烷基磷酸酯类"自乳化蜡"是与酯类（如甘油硬脂酸酯）、糖苷类等非离子乳化剂体系不同的独立类别：磷酸基在化妆品常见pH下部分电离，为界面提供额外的静电稳定作用，同时该体系以其成膜的耐水洗附着性著称。',
    en: 'A three-part waxy blend: Cetearyl Alcohol (a C16-18 fatty alcohol forming the emulsifying-wax base), Dicetyl Phosphate (a diester of phosphoric acid with two C16 cetyl-alcohol chains, leaving one ionizable phosphate group and so carrying anionic character), and Ceteth-10 Phosphate (cetyl alcohol ethoxylated with 10 moles of ethylene oxide, then esterified with phosphoric acid — combining an anionic phosphate head with a nonionic PEG chain). This alkyl-phosphate-ester "self-emulsifying wax" class is structurally distinct from ester-type (e.g. glyceryl stearate) or glucoside-type nonionic emulsifiers: the partially ionized phosphate groups add electrostatic interfacial stabilization on top of the steric stabilization from the fatty chains, and this chemistry class is well known in cosmetic formulation for producing wash-resistant, substantive films.',
  },
  structureFunctionAnalysis: [
    {
      aspect: { zh: '防水膜与SPF增效从何而来', en: 'Where the waterproof film and SPF-boosting effect come from' },
      explanation: {
        zh: '磷酸二鲸蜡酯与鲸蜡醇聚醚-10磷酸酯的阴离子磷酸头基彼此及与皮肤表面产生较强的离子/氢键缔合，配合鲸蜡硬脂醇的C16-18长链结晶形成连续疏水膜；这层膜比常规非离子酯类乳化剂形成的膜更耐水洗（供应商称"天然附着力"），因而能在皮肤表面保留更多油相及其中溶解的防晒剂，这是其被用于"增强防晒霜SPF"的结构基础。',
        en: "The anionic phosphate head groups of Dicetyl Phosphate and Ceteth-10 Phosphate associate strongly with each other and with the skin surface via ionic/hydrogen bonding, while the C16-18 chains of Cetearyl Alcohol crystallize into a continuous hydrophobic film; this film is more wash-resistant than films from conventional nonionic ester emulsifiers (supplier-described 'natural substantivity'), letting it retain more oil phase — and the UV filters dissolved in it — on the skin surface, which is the structural basis for its use in boosting sunscreen SPF.",
      },
    },
    {
      aspect: { zh: '油、水相活性物"同步快速释放"从何而来', en: 'Where the fast, simultaneous release of oil- and water-phase actives comes from' },
      explanation: {
        zh: '该体系兼具亲脂的鲸蜡硬脂醇与部分水溶、可形成层状液晶网络的磷酸酯组分；涂抹摩擦产生的剪切力会使这一液晶网络暂时破坏（供应商描述为剪切变稀/触变性），油相与水相因此同时被"挤出"释放，而非像单纯疏水膜那样只优先释放油相或需要更长时间溶胀释放水相活性物。',
        en: "The blend combines the lipophilic Cetearyl Alcohol with the partially water-dispersible, liquid-crystal-forming phosphate-ester components; the shear generated by rubbing the product onto skin transiently breaks down this liquid-crystal network (supplier-described as shear-thinning/thixotropic behavior), so both the oil and water phases are expressed together rather than the oil phase releasing preferentially while water-phase actives are held back in a slower-swelling network.",
      },
    },
    {
      aspect: { zh: '为何要复配非离子的鲸蜡醇聚醚-10磷酸酯，而非只用磷酸二鲸蜡酯', en: 'Why a nonionic ethoxylated component (Ceteth-10 Phosphate) is blended in rather than using dicetyl phosphate alone' },
      explanation: {
        zh: '单独的磷酸二鲸蜡酯是强亲脂性的长链二烷基磷酸酯，自身分散入水相的能力有限；加入经10摩尔环氧乙烷乙氧基化的鲸蜡醇磷酸酯后，体系整体的亲水程度被拉高到足以自发乳化分散于水相，而无需额外复配乳化剂，同时磷酸二鲸蜡酯仍保留其离子性、耐水膜特征——这是磷酸酯类乳化蜡中常见的"亲水组分平衡亲油蜡基"结构策略。',
        en: "Dicetyl Phosphate alone is a strongly lipophilic, long-chain dialkyl phosphate ester with limited ability to disperse into water on its own; adding the 10-mole-ethoxylated cetyl phosphate component raises the blend's overall hydrophilicity enough for the wax to self-emulsify directly into the water phase without a separate emulsifier, while Dicetyl Phosphate still contributes its ionic, water-resistant film character. This 'hydrophilic component balancing a lipophilic wax anchor' is a common structural strategy in alkyl-phosphate emulsifying waxes.",
      },
    },
  ],
  appearance: {
    zh: '白色蜡状薄片/颗粒（pastille），熔点约51-58°C（非直接查证，见flaggedFields）',
    en: 'white waxy pastilles, melting point approx. 51-58°C (not independently confirmed by direct fetch — see flaggedFields)',
  },
  performance: {
    skinFeel: {
      zh: '形成耐水洗、具附着力的膜层，供应商称能带来更高的油相沉积；肤感偏丰润，具一定成膜厚重感',
      en: 'forms a wash-resistant, substantive film; supplier describes greater oil deposition on skin — the skin feel leans rich, with some film-forming heaviness',
    },
    pillingTendency: 'unknown',
    emulsificationAbility: 'high',
    suspensionStabilization: 'unknown',
  },
  strengths: [
    {
      zh: '独特的乳化+成膜机制，可提升防水型防晒配方的SPF表现（供应商数据：更高的油相沉积与耐水洗附着力）',
      en: 'a distinctive emulsifying + film-forming mechanism that can boost SPF performance in waterproof sun-care formulas (supplier data: greater oil deposition and wash-resistant substantivity)',
    },
    {
      zh: '剪切变稀/触变性使油、水相活性物可同步快速释放（供应商数据）',
      en: 'shear-thinning/thixotropic behavior gives fast, simultaneous release of both oil- and water-phase actives (supplier data)',
    },
    {
      zh: '90%可再生、生物基来源，配方定位无防腐剂/无EDTA，具RSPO（质量平衡）、清真认证及素食友好标识，预期具固有生物降解性',
      en: '90% renewable/bio-based content, positioned as preservative-free and EDTA-free, carries RSPO (mass-balance) and Halal certification plus a vegan-suitable claim, and is expected to be inherently biodegradable',
    },
  ],
  weaknesses: [
    {
      zh: '含阴离子磷酸基，与阳离子成分（如季铵盐类调理剂/聚合物）复配时通常需要额外相容性验证，这是烷基磷酸酯类乳化剂的普遍特性',
      en: 'carries an anionic phosphate group, so compatibility with cationic ingredients (e.g. quaternary conditioning agents/polymers) typically needs extra verification — a general characteristic of alkyl-phosphate emulsifiers',
    },
    {
      zh: '为蜡状颗粒（pastille）形态，需加热熔融进行热法乳化，工艺上不如冷法乳化剂便捷',
      en: 'supplied as waxy pastilles, requiring hot-process (melt) emulsification, which is less convenient than cold-process emulsifiers',
    },
    {
      zh: 'HLB值与精确使用浓度等完整数据锁定于Croda需登录访问的技术数据表，公开渠道未能独立核实（见flaggedFields）',
      en: 'the full numeric TDS (HLB, precise recommended use level) sits behind Croda\'s login-gated technical data sheet and could not be independently confirmed via public sources (see flaggedFields)',
    },
  ],
  suitableSystems: [
    {
      system: { zh: '防水型防晒乳/喷雾（SPF增效）', en: 'waterproof sunscreen lotion/spray (SPF-boosting)' },
      notes: { zh: '供应商核心定位场景', en: "the supplier's core positioning use case" },
    },
    {
      system: { zh: '婴儿护理、彩妆、免洗/护发素类调理产品', en: 'baby care, color cosmetics, and rinse-off hair-conditioner-type conditioning products' },
    },
    {
      system: { zh: '晒后修护、身体护理、剃须/脱毛产品', en: 'after-sun, body care, and shaving/hair-removal products' },
    },
  ],
  typicalUseLevel: { min: 5, max: 8, unit: '%' },
  relatedIngredientSlugs: ['crodafos-cs20a', 'cetearyl-alcohol-ceteareth-20'],
  citations: [
    {
      id: 'crodabeauty-crodafos-ces-product-page',
      supplier: 'Croda Beauty',
      documentTitle: 'Crodafos™ CES | Croda Beauty (product page)',
      url: 'https://www.crodabeauty.com/en-gb/products/product/1972-crodafos_1_ces',
      accessedDate: '2026-08-06',
      note: 'Directly fetched. Used for INCI name, chemical family (phosphorous compounds), functions (emulsifier/active booster/effect ingredient), key performance description (natural substantivity, greater oil deposition, shear-thinning/thixotropy enabling fast simultaneous release of oil- and water-based actives), applications list, composition profile (90% renewable/bio-based, preservative-free/EDTA-free), certifications (RSPO mass balance, Halal, vegan suitable, IECIC), and biodegradability. The full technical data sheet (HLB, exact use level) requires a Croda account login and was not accessible in this session.',
    },
    {
      id: 'crodafos-ces-aggregated-appearance-uselevel',
      supplier: 'Croda (aggregated via SpecialChem / UL Prospector / Scribd-hosted PDS listings)',
      documentTitle: 'Crodafos CES — aggregated appearance, melting point, and use-level data',
      url: 'https://www.specialchem.com/cosmetics/product/croda-crodafos-ces',
      accessedDate: '2026-08-06',
      note: 'Appearance ("white pastilles," melting point 51-58°C) and recommended topical use level (5-8%) were found via a web-search summary drawing on SpecialChem/UL Prospector/Scribd-hosted listings; direct fetch of the SpecialChem product page returned HTTP 403 (login-gated) in this session, so these figures are not independently confirmed first-hand — see flaggedFields.',
    },
  ],
  dataCompleteness: 'partial',
  flaggedFields: ['appearance', 'typicalUseLevel'],
  lastUpdated: '2026-08-06',
})
