import { defineIngredient } from '../../../schema/defineIngredient'

export default defineIngredient({
  slug: 'kelco-care-diutan-gum',
  category: 'polymer',
  inciName: 'Diutan Gum',
  nameZh: '双糖胶（Diutan胶）',
  tradeNames: [{ name: 'Kelco-Care', supplier: 'CP Kelco' }],
  chemicalClass: {
    zh: '发酵法阴离子微生物多糖（鞘氨胶/sphingan家族，鞘氨醇单胞菌属发酵产物）',
    en: 'Fermentation-derived anionic microbial polysaccharide (a "sphingan"-family biopolymer, produced by Sphingomonas sp. fermentation)',
  },
  chemicalStructureSummary: {
    zh: '由鞘氨醇单胞菌（Sphingomonas sp.）发酵产生，与结冷胶（Gellan Gum）同属"鞘氨胶（sphingan）"家族，共享相同的四糖主链（D-葡萄糖-D-葡萄糖醛酸-D-葡萄糖-L-鼠李糖）。与结冷胶不同的是，双糖胶在主链上的一个葡萄糖残基上还带有一条由两个鼠李糖组成的侧链——这是"diutan（双糖）"命名的来源，也是其与结冷胶（无侧链）、黄原胶等其他微生物多糖的关键结构区别。该侧链在水中围绕主链缠绕，促使分子采取更稳定的双螺旋构象；主链上葡萄糖醛酸的羧基使整个分子呈阴离子性。',
    en: 'Produced by fermenting Sphingomonas sp. bacteria, diutan gum belongs to the same "sphingan" family of biopolymers as gellan gum and shares the same tetrasaccharide backbone (D-glucose - D-glucuronic acid - D-glucose - L-rhamnose). Unlike gellan gum, diutan gum carries an additional side chain of two rhamnose residues attached to one of the backbone glucose residues — the structural feature behind the "di-" (two rhamnose) in its name, and the key structural difference from gellan gum (no side chain) and other microbial polysaccharides like xanthan gum. In water, this side chain wraps around the backbone, promoting a stable double-helical conformation; the carboxyl groups on the backbone glucuronic-acid residues give the molecule its overall anionic character.',
  },
  structureFunctionAnalysis: [
    {
      aspect: { zh: '低用量下高效增稠从何而来', en: 'Where the high thickening efficiency at low use levels comes from' },
      explanation: {
        zh: '鼠李糖侧链缠绕主链形成稳定的双螺旋结构，使分子链呈现较大的流体力学体积与刚性；这类刚性、大体积的螺旋链在溶液中彼此交叠、缔合即可形成跨越体系的粘弹网络，因此供应商将其定位为"在较低总固含量下即高效的粘度构建剂"——即用较低添加量即可达到目标粘度。',
        en: 'The rhamnose side chain wraps around the backbone to form a stable double-helical structure, giving the molecule a comparatively large hydrodynamic volume and rigidity. Such rigid, bulky helical chains readily overlap and associate with one another in solution to form a viscoelastic network spanning the system, which is the basis for the supplier positioning it as "a very efficient viscosity builder at lower total solids" — i.e. reaching target viscosity at a lower use level than many alternative gums.',
      },
    },
    {
      aspect: { zh: '不同于结冷胶的"非阳离子触发"电解质耐受从何而来', en: 'Where the ("non-cation-triggered") electrolyte tolerance — distinct from gellan gum — comes from' },
      explanation: {
        zh: '双糖胶的双螺旋主要由分子内鼠李糖侧链缠绕自身主链稳定形成，而非像结冷胶那样依赖阳离子在链间"架桥"才能聚集成网络；其增稠网络主要来自螺旋链之间的物理缠结与缔合，而非严格依赖阳离子屏蔽羧酸根电荷这一单一机制。因此体系中引入电解质或阳离子成分时，双糖胶不会像结冷胶那样被动依赖阳离子触发骤然成胶，粘度/流变性能在宽电解质浓度与阳离子种类范围内相对更稳定——这是供应商所述"耐电解质"和"与阳离子成分兼容"的结构基础。',
        en: "Diutan gum's double helix is stabilized mainly by the rhamnose side chain wrapping around its own backbone (an intramolecular effect), rather than requiring cations to \"bridge\" between chains to aggregate into a network the way gellan gum does. Its thickening network arises mainly from physical entanglement/association between helical chains rather than depending strictly on cation-screening of carboxylate charge as gellan gum's single dominant mechanism. Consequently, when electrolytes or cationic ingredients are introduced into a formula, diutan gum does not passively depend on cation-triggered sudden gelling the way gellan gum does, and its viscosity/rheology stays comparatively more stable across a wide range of electrolyte concentrations and cation types — the structural basis for the supplier-described \"electrolyte resistant\" behavior and compatibility with cationic species.",
      },
    },
    {
      aspect: { zh: '剪切变稀、丝滑肤感从何而来', en: 'Where the shear-thinning rheology and silky skin feel come from' },
      explanation: {
        zh: '静置时刚性螺旋链彼此缠绕缔合形成粘弹网络，赋予体系较高的静态粘度；涂抹或搅拌产生的剪切力使螺旋链沿流场取向、缠结点被拆散，粘度随之下降，供应商描述为"利于顺滑流动的剪切变稀流变性"；停止剪切后网络重新缔合、粘度恢复，兼具静置稳定与涂抹轻盈两种特性，这也是供应商所述"丝滑、轻盈肤感"的结构基础。',
        en: 'At rest, the rigid helical chains entangle and associate into a viscoelastic network, giving the system relatively high static viscosity; the shear generated by application or stirring aligns the helical chains with the flow and breaks apart the entanglement points, dropping viscosity — described by the supplier as "shear-thinning rheology for smooth flow." Once shear stops, the network re-associates and viscosity recovers, giving both resting stability and light application feel — also the structural basis for the supplier-described "silky and smooth," "light" skin feel.',
      },
    },
  ],
  performance: {
    skinFeel: {
      zh: '供应商描述为"丝滑顺滑"且"轻盈"的肤感，兼具剪切变稀特性，涂抹流动顺畅、无明显滴落感（如发用产品中）',
      en: 'described by the supplier as giving a "silky and smooth," "light" skin feel with shear-thinning rheology for smooth flow and no noticeable dripping (e.g. in hair-care applications)',
    },
    pillingTendency: 'low',
    emulsificationAbility: 'low',
    pillingNotes: {
      zh: '供应商功能标签含增稠剂、悬浮剂、乳液稳定剂，本身非传统乳化剂',
      en: 'supplier functional tags include thickener, suspending agent, and emulsion stabilizer; not a conventional emulsifier itself',
    },
    suspensionStabilization: 'high',
  },
  strengths: [
    {
      zh: '供应商定位为"极高效"的粘度构建剂，较低总固含量下即可达到目标粘度',
      en: 'positioned by the supplier as a very efficient viscosity builder — reaches target viscosity at lower total solids than many alternatives',
    },
    {
      zh: '耐电解质、宽pH范围内性能稳定，且与阳离子成分兼容（供应商数据：因其阴离子特性而与阳离子原料兼容性增强）',
      en: 'electrolyte-resistant and stable across a broad pH range, with compatibility with cationic ingredients (supplier data: enhanced compatibility with cationic ingredients attributed to its anionic character)',
    },
    {
      zh: '耐纤维素酶/淀粉酶降解，宽温度范围内保持长期粘度与稳定性（供应商数据），发酵法可生物降解',
      en: 'resistant to cellulase/amylase enzymatic degradation and maintains long-term viscosity/stability across a broad temperature range (supplier data); a fermentation-derived, readily biodegradable ingredient',
    },
  ],
  weaknesses: [
    {
      zh: '本次检索未能获取推荐用量、外观形态及具体粘度数值等供应商定量数据，相关字段暂标记为未验证',
      en: 'this research pass could not obtain supplier quantitative data for recommended use level, physical appearance/form, or specific viscosity figures — these fields are flagged as unverified',
    },
    {
      zh: '作为发酵多糖类原料，一般仍建议做配方防腐体系验证以避免微生物降解影响粘度稳定性',
      en: 'as a fermentation-derived polysaccharide, formulators generally still need to verify the preservation system to prevent microbial degradation from affecting viscosity stability',
    },
    {
      zh: '与结冷胶同属鞘氨胶家族但胶凝机制不同，不能简单按结冷胶的阳离子成胶参数直接套用配方',
      en: 'though in the same sphingan family as gellan gum, its gelling mechanism differs — formulators cannot simply reuse gellan gum\'s cation-triggered gelling parameters when substituting one for the other',
    },
  ],
  suitableSystems: [
    {
      system: { zh: '护发素、染发/护色产品', en: 'hair conditioners, hair colorants/color-care products' },
      notes: { zh: '供应商数据：无滴落感，适合发用产品', en: 'supplier data: no-drip behavior suited to hair-care products' },
    },
    {
      system: { zh: '防晒产品', en: 'sun care products' },
    },
    {
      system: { zh: '洁肤/护肤产品的增稠悬浮稳定', en: 'thickening/suspension stabilization in cleansing and skin care products' },
    },
  ],
  relatedIngredientSlugs: ['kelcogel-gellan-gum', 'xanthan-gum', 'sclerotium-gum'],
  citations: [
    {
      id: 'lubrizol-kelcocare-search',
      supplier: 'Lubrizol / CP Kelco (indexed search snippets)',
      documentTitle: 'Kelco-Care™ Diutan Gum — product description (Lubrizol Beauty solutions page)',
      url: 'https://www.lubrizol.com/solutions/products/beauty/detail-pages/kelco-care-diutan-gum',
      accessedDate: '2026-08-06',
      note: 'Used for "fermentation-derived rheology modifier," "readily biodegradable," "electrolyte resistant," "effective across broad pH ranges," "compatible with cationic species," "cold processable," "silky and smooth skin feel," and thermal-stability/high-alcohol-and-polyol-compatibility claims. Note: CP Kelco is now part of Lubrizol\'s beauty/personal-care portfolio. Direct fetch returned HTTP 403 in this session; content is from a web-search snippet of this supplier page, not independently confirmed against the full page.',
    },
    {
      id: 'ulprospector-kelcocare-search',
      supplier: 'UL Prospector (indexed search snippet)',
      documentTitle: 'Kelco-Care diutan gum — Personal Care & Cosmetics product listing',
      url: 'https://www.ulprospector.com/en/na/PersonalCare/Detail/76/1423124/Kelco-Care-diutan-gum',
      accessedDate: '2026-08-06',
      note: 'Used for INCI confirmation ("Diutan gum"), applications (hair conditioners, hair colorants, sun care, conditioning/cleansing products, skin care), "enhanced compatibility with cationic ingredients due to its anionic character," "shear-thinning rheology for smooth flow," "very efficient viscosity builder at lower total solids," and cellulase/amylase resistance. Direct fetch returned HTTP 403; content is from a web-search snippet, not independently confirmed against the full page.',
    },
    {
      id: 'search-diutan-gum-cosing-inci',
      supplier: 'CosIng (EU Commission cosmetic ingredient database, indexed search snippet)',
      documentTitle: 'Diutan Gum — INCI/CosIng entry (CosIng ref. 96554)',
      accessedDate: '2026-08-06',
      note: 'Used to confirm "Diutan Gum" as the standalone INCI name (CAS 125005-87-0, EC 603-019-8), distinct from Gellan Gum and from Sphingomonas Ferment Extract (a differently-INCI-labeled listing seen on one distributor page was not used, as CosIng and the primary CP Kelco-linked listings consistently confirm "Diutan Gum" as the INCI). Direct fetch of the CosIng database page was blocked in this session; confirmed via search-result snippet only.',
    },
    {
      id: 'search-diutan-gum-structure',
      supplier: 'Published polysaccharide-chemistry literature and industry technical sources (indexed excerpts)',
      documentTitle: 'Diutan gum molecular structure — sphingan family backbone and rhamnose side chain (vs. gellan gum)',
      accessedDate: '2026-08-06',
      note: 'Backbone composition (D-glucose, D-glucuronic acid, D-glucose, L-rhamnose repeat unit shared with gellan/S-88 sphingans) and the distinguishing two-rhamnose side chain (vs. no side chain for gellan) found via web-search snippets of published/industry polysaccharide-chemistry sources; exact wording not independently confirmed against a single fetched primary document in this session.',
    },
  ],
  dataCompleteness: 'partial',
  flaggedFields: ['typicalUseLevel', 'appearance'],
  lastUpdated: '2026-08-06',
})
